[project]
name = "wangup-doc"
version = "0.1.0"
description = "Hydrometerology Lab Computing Documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-material>=9.5.0",
    "pymdown-extensions>=10.7",
]
